

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [1]:
import numpy as np

In [4]:
x = np.zeros(10)

In [5]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
y = np.zeros(10)
y[4]=1

In [17]:
y

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [18]:
a = np.arange(10,49)

In [19]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [29]:
b = np.arange(0, 9).reshape((3, 3))

In [30]:
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
b = [1,2,0,0,4,0]
b = np.nonzero(b)
print(b)


(array([0, 1, 4]),)


In [39]:
c = np.eye(3,3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
d = np.random.random((3, 3, 3))
d

array([[[0.76788745, 0.94176318, 0.02266261],
        [0.61263548, 0.94228647, 0.12738639],
        [0.48829633, 0.62113435, 0.83169407]],

       [[0.039614  , 0.69219475, 0.4798604 ],
        [0.03186418, 0.18987679, 0.70097871],
        [0.47206418, 0.10938974, 0.31769621]],

       [[0.56140775, 0.74962999, 0.30653998],
        [0.05607295, 0.61444054, 0.56693644],
        [0.81851982, 0.32849869, 0.63270712]]])

In [71]:
e = np.random.random((10, 10))
e

array([[0.50913312, 0.34350414, 0.7964086 , 0.12144467, 0.01700206,
        0.16482913, 0.77666367, 0.34174539, 0.20486402, 0.45984957],
       [0.76216492, 0.54898103, 0.29829349, 0.07464433, 0.84821667,
        0.3003174 , 0.36487155, 0.81383462, 0.6394039 , 0.04622653],
       [0.47610172, 0.49740812, 0.7397242 , 0.47599919, 0.41299674,
        0.6340571 , 0.9939849 , 0.2984719 , 0.13068016, 0.94764754],
       [0.08540347, 0.38033208, 0.79123694, 0.89640523, 0.05468717,
        0.7952179 , 0.02758104, 0.00510751, 0.92871329, 0.23412156],
       [0.46900434, 0.70290689, 0.24186259, 0.26816928, 0.05510665,
        0.75878125, 0.13855198, 0.16244016, 0.18293581, 0.28396144],
       [0.47741365, 0.31964827, 0.38282611, 0.53259314, 0.5276881 ,
        0.28730553, 0.84375364, 0.05351352, 0.92302061, 0.31377639],
       [0.20363536, 0.23301869, 0.79220697, 0.7781381 , 0.27265765,
        0.95855923, 0.89932832, 0.21212482, 0.868796  , 0.08857223],
       [0.68974978, 0.1662138 , 0.8314393

In [73]:
e_max = np.max(e)
print(e_max)

0.998697042660289


In [74]:
e_min = np.min(e)
print(e_min)

0.0012961679443570517


In [76]:
f = np.random.random(30)
f

array([0.56781534, 0.48888058, 0.71737879, 0.71971809, 0.83498896,
       0.84251321, 0.90261063, 0.14471746, 0.75343698, 0.83755669,
       0.50852972, 0.23269101, 0.25713609, 0.54840276, 0.21375081,
       0.94312376, 0.05735756, 0.69479444, 0.83450931, 0.59076999,
       0.7037585 , 0.72644735, 0.93477919, 0.92724311, 0.67871225,
       0.67620571, 0.66860086, 0.63374045, 0.65866394, 0.98604308])

In [77]:
f_mean = np.mean(f)
print(f_mean)

0.6428292205399182


In [123]:
g = np.diag(1 + np.arange(4), k = -1)
g

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [90]:
h= np.random.random((5,5))

hmax, hmin = h.max(), h.min()
h= (h-hmin)/(hmax-hmin)
print (h)

[[1.         0.37125324 0.03687619 0.80406606 0.14152867]
 [0.61597652 0.16234718 0.         0.25560783 0.76039583]
 [0.78811705 0.67019929 0.95382271 0.1225176  0.09207691]
 [0.37946777 0.88194106 0.0472166  0.1771801  0.95029391]
 [0.46023966 0.04979521 0.9010879  0.33495531 0.00173319]]


In [97]:
i = np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
i


array([1, 3])

In [100]:
l = np.random.random(5)
l_1 = np.sort(l)

l_1



array([0.26130476, 0.53644146, 0.57930483, 0.78108895, 0.91064745])

In [102]:
m = np.random.random(10)
m

array([0.68480816, 0.54216974, 0.48904167, 0.09899511, 0.71270397,
       0.60073673, 0.55767785, 0.49392216, 0.94632902, 0.87690273])

In [106]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.97207619 0.67999416 0.47263926 0.         0.22684157 0.79980704
 0.61823193 0.49127268 0.31397385 0.95737307]


In [120]:
n = np.matrix([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
n

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [121]:
o = n - n.mean(axis=1).reshape(-1, 1)
o

matrix([[-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.]])

In [124]:
p = np.arange(10000)
p

array([   0,    1,    2, ..., 9997, 9998, 9999])